export const GAME_THUMB_FIELDS = [
  "id",
  "title",
  "slug",
  "release_year",
  "family_sharing",
  "game_status",
  "player_status",
  "cover_image.id",
  "cover_image.filename_disk",
  "genres.id",
  "genres.genres_id.id",
  "genres.genres_id.name",
  "genres.genres_id.slug",
  "engines.id",
  "engines.engines_id.id",
  "engines.engines_id.title",
  "engines.engines_id.slug",
  "developers.id",
  "developers.developers_id.id",
  "developers.developers_id.name",
  "developers.developers_id.slug",
  "links.id",
  "links.url",
  "links.label",
  "links.kind",
  "links.sort",
];

export const DEVELOPER_LINK_FIELDS = [
  "links.id",
  "links.url",
  "links.label",
  "links.kind",
];
