version: 2
updates:
- package-ecosystem: npm
  directory: /site
  schedule:
    interval: weekly
  auto-merge: enable
- package-ecosystem: docker
  directory: /
  schedule:
    interval: weekly
  auto-merge: enable
- package-ecosystem: docker
  directory: /builder
  schedule:
    interval: weekly
  auto-merge: enable
