version: 2
updates:
- package-ecosystem: npm
  directory: /site
  schedule:
    interval: weekly
  reviewers:
  - jasmeralia
- package-ecosystem: docker
  directory: /builder
  schedule:
    interval: weekly
  reviewers:
  - jasmeralia
- package-ecosystem: pip
  directory: /mcp
  schedule:
    interval: weekly
  reviewers:
  - jasmeralia
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  reviewers:
  - jasmeralia
