coverage:
  status:
    project:
      default:
        target: 80%
        informational: true
    patch:
      default:
        target: 80%
        informational: true

comment:
  layout: "reach, diff, flags, files"
  require_changes: true

ignore:
  - "site/src/**/*.test.ts"
  - "site/src/test/**"
